#!/usr/bin/env python3
"""Build RGB residual tiles from an aligned-pair manifest with valid-byte masks.

This entrypoint is intended for the facade monitoring RGB experiment. It reads
``pairs_all.csv`` generated by Compress_to_prevent, therefore alignment is not
recomputed and no heuristic asset lookup is used. The saved residual is
``current - warped_previous (mod 256)``. Invalid aligned pixels are set to zero
for context and excluded from loss/scoring through a parallel byte-valid mask.

The current quantitative protocol uses non-overlapping tiles, i.e.
``stride == tile_size``. This keeps tile coordinates directly compatible with
the GT-reference evaluator.
"""
from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Dict, Iterable, List, Sequence

import cv2
import numpy as np


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build valid-masked aligned RGB residual tiles.")
    parser.add_argument("--pairs-manifest", type=Path, required=True)
    parser.add_argument("--out-root", type=Path, required=True)
    parser.add_argument("--tile-size", type=int, default=32)
    parser.add_argument("--stride", type=int, default=32)
    parser.add_argument("--train-min-valid-fraction", type=float, default=0.90)
    parser.add_argument("--eval-min-valid-fraction", type=float, default=0.50)
    parser.add_argument("--valid-threshold", type=int, default=0)
    parser.add_argument("--write-viz", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--overwrite", action="store_true")
    return parser.parse_args()


def read_csv(path: Path) -> List[Dict[str, str]]:
    with path.open("r", newline="", encoding="utf-8") as handle:
        return [{str(key): (value or "") for key, value in row.items()} for row in csv.DictReader(handle)]


def write_csv(path: Path, fields: Sequence[str], rows: Iterable[Dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(fields))
        writer.writeheader()
        writer.writerows(rows)


def read_rgb(path: Path) -> np.ndarray:
    image = cv2.imread(str(path), cv2.IMREAD_COLOR)
    if image is None:
        raise FileNotFoundError("Could not read RGB image: {}".format(path))
    return cv2.cvtColor(image, cv2.COLOR_BGR2RGB)


def read_valid(path: Path, expected_shape: tuple[int, int], threshold: int) -> np.ndarray:
    image = cv2.imread(str(path), cv2.IMREAD_UNCHANGED)
    if image is None:
        raise FileNotFoundError("Could not read valid mask: {}".format(path))
    if image.ndim == 3:
        image = image[..., 0]
    if image.shape != expected_shape:
        raise ValueError("Valid-mask shape mismatch: expected={} got={} for {}".format(expected_shape, image.shape, path))
    return image > threshold


def modular_residual(current: np.ndarray, previous_aligned: np.ndarray) -> np.ndarray:
    return ((current.astype(np.int16) - previous_aligned.astype(np.int16)) % 256).astype(np.uint8)


def main() -> None:
    args = parse_args()
    if args.tile_size <= 0 or args.stride <= 0:
        raise ValueError("tile-size and stride must be positive")
    if args.stride != args.tile_size:
        raise ValueError("For the current tile-level evaluation protocol, use stride == tile-size.")
    if not 0.0 <= args.train_min_valid_fraction <= 1.0 or not 0.0 <= args.eval_min_valid_fraction <= 1.0:
        raise ValueError("valid-fraction thresholds must be in [0, 1]")

    rows = read_csv(args.pairs_manifest)
    required = {"pair_id", "facade_id", "curr_image_path", "prev_aligned_path", "valid_mask_path", "split"}
    if not rows or not required.issubset(rows[0]):
        raise ValueError("Aligned pair manifest must contain columns: {}".format(sorted(required)))

    if args.out_root.exists() and any(args.out_root.iterdir()) and not args.overwrite:
        raise FileExistsError("Output root is non-empty: {}. Pass --overwrite.".format(args.out_root))
    args.out_root.mkdir(parents=True, exist_ok=True)
    (args.out_root / "tiles").mkdir(parents=True, exist_ok=True)
    (args.out_root / "pairs").mkdir(parents=True, exist_ok=True)

    tile_rows: List[Dict[str, object]] = []
    pair_rows: List[Dict[str, object]] = []
    split_map: Dict[str, List[str]] = {}

    for row in rows:
        pair_id = row["pair_id"]
        split = row["split"]
        threshold = args.train_min_valid_fraction if split == "train" else args.eval_min_valid_fraction
        current = read_rgb(Path(row["curr_image_path"]))
        previous = read_rgb(Path(row["prev_aligned_path"]))
        if current.shape != previous.shape:
            raise ValueError("RGB shape mismatch for {}: current={} previous={}".format(pair_id, current.shape, previous.shape))
        valid = read_valid(Path(row["valid_mask_path"]), current.shape[:2], args.valid_threshold)
        residual = modular_residual(current, previous)
        residual[~valid] = 0
        height, width = residual.shape[:2]

        pair_dir = args.out_root / "pairs" / pair_id
        pair_dir.mkdir(parents=True, exist_ok=True)
        if args.write_viz:
            cv2.imwrite(str(pair_dir / "cur_rgb.png"), cv2.cvtColor(current, cv2.COLOR_RGB2BGR))
            cv2.imwrite(str(pair_dir / "prev_aligned_rgb.png"), cv2.cvtColor(previous, cv2.COLOR_RGB2BGR))
            cv2.imwrite(str(pair_dir / "residual_mod_rgb.png"), cv2.cvtColor(residual, cv2.COLOR_RGB2BGR))
            cv2.imwrite(str(pair_dir / "valid_mask.png"), valid.astype(np.uint8) * 255)

        sequences: List[np.ndarray] = []
        valid_sequences: List[np.ndarray] = []
        tile_yx: List[tuple[int, int]] = []
        valid_fractions: List[float] = []
        for y in range(0, height - args.tile_size + 1, args.stride):
            for x in range(0, width - args.tile_size + 1, args.stride):
                valid_tile = valid[y:y + args.tile_size, x:x + args.tile_size]
                fraction = float(valid_tile.mean())
                if fraction < threshold:
                    continue
                tile = residual[y:y + args.tile_size, x:x + args.tile_size]
                byte_valid = np.repeat(valid_tile[..., None], 3, axis=2).reshape(-1).astype(np.uint8)
                sequences.append(tile.reshape(-1).astype(np.uint8))
                valid_sequences.append(byte_valid)
                tile_yx.append((y, x))
                valid_fractions.append(fraction)
                tile_rows.append({
                    "pair_id": pair_id,
                    "facade_id": row["facade_id"],
                    "split": split,
                    "tile_origin_y": y,
                    "tile_origin_x": x,
                    "tile_y": y // args.tile_size,
                    "tile_x": x // args.tile_size,
                    "tile_size": args.tile_size,
                    "valid_fraction": fraction,
                    "valid_byte_count": int(byte_valid.sum()),
                })

        if sequences:
            np.savez_compressed(
                args.out_root / "tiles" / (pair_id + ".npz"),
                sequences=np.stack(sequences),
                valid_sequences=np.stack(valid_sequences),
                tile_yx=np.asarray(tile_yx, dtype=np.int32),
                valid_fraction=np.asarray(valid_fractions, dtype=np.float32),
                tile_size=np.int32(args.tile_size),
                stride=np.int32(args.stride),
                H=np.int32(height),
                W=np.int32(width),
            )
        pair_rows.append({
            "pair_id": pair_id,
            "facade_id": row["facade_id"],
            "split": split,
            "curr_image_path": row["curr_image_path"],
            "prev_aligned_path": row["prev_aligned_path"],
            "valid_mask_path": row["valid_mask_path"],
            "height": height,
            "width": width,
            "pair_valid_ratio": float(valid.mean()),
            "min_valid_fraction": threshold,
            "n_tiles": len(sequences),
        })
        split_map.setdefault(split, []).append(pair_id)

    write_csv(args.out_root / "tile_metadata.csv", list(tile_rows[0].keys()) if tile_rows else ["pair_id"], tile_rows)
    write_csv(args.out_root / "pair_metadata.csv", list(pair_rows[0].keys()) if pair_rows else ["pair_id"], pair_rows)
    splits_dir = args.out_root / "splits"
    splits_dir.mkdir(parents=True, exist_ok=True)
    for split, pair_ids in split_map.items():
        (splits_dir / ("facade_" + split + ".txt")).write_text("\n".join(sorted(set(pair_ids))) + "\n", encoding="utf-8")

    by_split = {split: sum(1 for item in pair_rows if item["split"] == split) for split in sorted(split_map)}
    tiles_by_split = {split: sum(1 for item in tile_rows if item["split"] == split) for split in sorted(split_map)}
    report = {
        "pairs_manifest": str(args.pairs_manifest),
        "tile_size": args.tile_size,
        "stride": args.stride,
        "train_min_valid_fraction": args.train_min_valid_fraction,
        "eval_min_valid_fraction": args.eval_min_valid_fraction,
        "pairs_by_split": by_split,
        "tiles_by_split": tiles_by_split,
        "n_tiles": len(tile_rows),
        "residual_definition": "current RGB minus warped previous RGB modulo 256",
        "validity_policy": "invalid residual bytes are zero context values and are excluded as loss/score targets",
    }
    (args.out_root / "dataset_report.json").write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")
    print("Built RGB residual byte-tile dataset")
    print("Pairs by split:", by_split)
    print("Tiles by split:", tiles_by_split)
    print("Report:", args.out_root / "dataset_report.json")


if __name__ == "__main__":
    main()
